### send to default
POST http://localhost:3978/api/notify/default

### send to members
POST http://localhost:3978/api/notify/members

### send to channels
POST http://localhost:3978/api/notify/channels

### send to configured channels
POST http://localhost:3978/api/notify/configured

### send reply to existing conversation
POST http://localhost:3978/api/notify/reply
